### ISSUE TITLE
Login feature does not work.

### ISSUE THREAD

**Issue by longnd** [nvminhtue/coding_challenge#18]
Hi Tue 👋
Thank you for the effort spent on this code challenge.
I'm Long Nguyen, a software developer from Nimble, and I would like to conduct the feedback via Gitlab Issues regarding your code challenge.
Keep in mind, this is a bidirectional process, so I would love to hear back from you as well, so please do not hesitate to raise your question/correction in case I missed anything.
If we are aligned on any issue here and you would like to correct them, please go ahead and open a Pull Request per fix, merge it when you feel confident and I will follow up on these fixes 😇
I hope you find the process enjoyable. Good luck and happy coding

---

The first issue I notice is that the login feature doesn't work as expected when I check the app [deployed on Heroku](https://google-massive-searching.herokuapp.com/):
Both fields are email
<img width="434" alt="Screen Shot 2022-04-04 at 16 30 09" src="https://user-images.githubusercontent.com/1896814/161515850-9b51db35-b092-4bf5-af08-072dd6f2b8ee.png">

so there is no chance for the user to provide the password
<img width="409" alt="Screen Shot 2022-04-04 at 16 32 36" src="https://user-images.githubusercontent.com/1896814/161516292-c179dd17-9cb4-4e7b-8930-919b70655f3a.png">

**Comment by nvminhtue** [comment]
@longnd It's a shame when you got stuck in the very first step, that's my responsibility. However, somehow I could not re-produce your met behavior. Please let me know your reproduced device/kind of browser or any chance caused by personal add-ons. I will try to reproduce and fix that problem
![image](https://user-images.githubusercontent.com/42540264/161517419-65d5a6af-c63f-472a-b592-03e7ed21707b.png)

**Comment by nvminhtue** [comment]
@longnd Actually, I found the reason that may be you installed 'Firefox Relay' extension on Firefox, which cause problem by pushing index of email field (belonged to register form) - coincident replace the position of password field on Login form itself.

I believe it's where the problem occurs. Please take a look once again by disable the Firefox Relay add-on temporary or start testing on incognito - private browser sessions.

In case of inconvenience, just let me know and let the issue remain with Open status, I will try to figure out how to adapt my app with these kind of extensions.

![image](https://user-images.githubusercontent.com/42540264/161699671-24d0ef1c-a0da-47f2-bc2b-30340bcbaddb.png)

**Comment by longnd** [comment]
hi Tue, I'm about to share the same issue that it's browser-specific issue. I tested on Chrome and it works. Good to know that's because of my extension. Thanks you for clarifying. 
I can now access the site on Heroku 😇
