### ISSUE TITLE
Project setup instructions

### ISSUE THREAD

**Issue by longnd** [nvminhtue/coding_challenge#20]
The README file is empty. It would be great if it gets some love to instruct the other developers than you on how to set up the project, e.g. the system requirements (nodejs version, ...), what are the expected steps to set up and run it on a local environment.

Besides that, have you considered using Docker and Docker Compose to easily set up dependencies, e.g. databases? Do you have experience in using these tools?

**Comment by nvminhtue** [comment]
@longnd I've pushed a improved README.md file, please take a look on this PR: https://github.com/nvminhtue/coding_challenge/pull/25

**Comment by longnd** [comment]
hi Tue, thank you for the update. It looks way more comprehensive now 👍
