### ISSUE TITLE
Mix of typescript and javascript files

### ISSUE THREAD

**Issue by longnd** [nvminhtue/coding_challenge#21]
I'm aware that you're using both typescript (for the server part) and vanillaJS (for the client part). It seems you decided to switch to JS since this PR #6. I'm wondering what is the motivation for that change, why don't you use typescript for the entire project?

**Comment by nvminhtue** [comment]
@longnd I have to confess that I'm not usually using TS on ReactJS projects, sadly I decided to use it in this coding challenge but quickly realize there are a bunch of errors that showed up that could heavily affect my working progress. I have to choose the higher priority and sacrifice TS on the client-side  - `ReactTS`  :pepe-sad:. I will practice more to be fully migrated into Typescript in future projects.
